### ISSUE TITLE
How can I send a message on startup to a user? 

### ISSUE THREAD

**Issue by ghostrider** [wondergram-org/wonda#8]
### Question

Hi there
the event system works well - on message, I can react to that message. 
However, how can the bot send a message to a particular user, not as response to an incoming message? 

For example when I start up the bot, I want the bot to send a message to my other telegram account? 

 
Thanks

**Comment by kikimaradoni** [comment]
Hello there! To perform tasks on startup, you can use the loop wrapper functionality. A loop wrapper manages tasks inside the event loop of the application. It's created for you automatically when you initialize a Bot object. 

Using this utility, it's very easy to send a message on startup:

```python
async def send_message() -> None:
    await bot.api.send_message(...)

bot.loop_wrapper.on_startup.append(send_message())
bot.run_forever()
```

More on using loop wrapper: https://github.com/wondergram-org/wonda/blob/main/examples/loop_wrapper_usage.py
